### ISSUE TITLE
Unable to install timesfm due to lingvo

### ISSUE THREAD

**Issue by vkaltasv** [Sakil786/Time-Series-Forecasting-Using-LLM#1]
When trying to install the packages I keep running into lingvo not recognised command.
Steps to reproduce:
1. pip install -r requirements.txt
2. Get the following error:
ERROR: Could not find a version that satisfies the requirement lingvo (from versions: none)
ERROR: No matching distribution found for lingvo

**Comment by Sakil786** [comment]
Please try to use Google colab and once try to execute the code.

**Comment by vkaltasv** [comment]
@Sakil786 How? Any links would be appreciated.
Thanks

**Comment by Sakil786** [comment]
Please follow the following instructions:
1. Open Google colab
2. Upload all the files(Gold_price_data.csv,requirements.txt,cross_val_split.py,util.py,predict.py,main.py)
3. ! pip install -r requirements.txt
4. Run main.py
You will get the output.

**Comment by vkaltasv** [comment]
Thanks @Sakil786 for sharing this.
